name: Deploy MoodZen App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 13.60.171.206
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/moodzen
          git pull origin main
          docker stop moodzen_app || true
          docker rm moodzen_app || true
          docker build -t moodzen .
          docker run -d -p 8501:8501 --name moodzen_app moodzen
