name: Deploy App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2 Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 16.170.201.32
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/app
          git pull origin main
          docker-compose down
          docker-compose up -d --build
